using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CatteryManagerLib
{
    public enum CatBreeds
    {
        Abyssinian,
        AmericanBobtail,
        AmericanCurl,
        AmericanShorthair,
        AmericanWirehair,
        Balinese,
        Bengal,
        Birman,
        Bombay,
        BritishShorthair,
        Burmese,
        Burmilla,
        Chartreux,
        CornishRex,
        Cymric,
        DevonRex,
        EgyptianMau,
        EuropeanShorthair,
        ExoticShorthair,
        HavanaBrown,
        Himalayan,
        JapaneseBobtail,
        Javanese,
        KhaoManee,
        Korat,
        KurilianBobtail,
        LaPerm,
        MaineCoon,
        Manx,
        Munchkin,
        NorwegianForestCat,
        Ocicat,
        OrientalShorthair,
        Persian,
        Peterbald,
        Pixiebob,
        Ragamuffin,
        Ragdoll,
        RussianBlue,
        ScottishFold,
        SelkirkRex,
        Siamese,
        Siberian,
        Singapura,
        Snowshoe,
        Somali,
        Sphynx,
        Tonkinese,
        TurkishAngora,
        TurkishVan,
        YorkChocolate,
        Serengeti,
        Chausie,
        Toyger,
        BengalLonghair,
        BengalShorthair,
        ScottishStraight,
        ExoticLonghair,
        HimalayanLonghair,
        PersianExotic,
        OrientalLonghair,
        BritishLonghair,
        CornishRexLonghair,
        DevonRexLonghair,
        LaPermLonghair
    }
}
