services:
#Server Web (php)
  web:
    image: php:8.2-apache # L'immagine Docker ufficiale di PHP con Apache
    ports:
      - "8080:80" # Espone la porta 80 del container sulla porta 8080 del host
    volumes:
      - ./:/var/www/html # Monta la directory src del host nella directory /var/www/html del container
    depends_on:
      - db # Indica che il servizio web dipende dal servizio db, quindi Docker avvierà prima il database.
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password_segreta
    volumes:
      - db_data:/var/lib/mysql
